import { Element } from "./types";
import { nanoid } from "nanoid";

export const getInitialContent = (): Element[] => [
    {
        id: nanoid(),
        type: "text",
        x: 100,
        y: 100,
        width: 400,
        height: 60,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        strokeWidth: 2,
        roughness: 1,
        opacity: 100,
        text: "Welcome to my Portfolio!",
        seed: 1,
    },
    {
        id: nanoid(),
        type: "rectangle",
        x: 100,
        y: 200,
        width: 200,
        height: 100,
        strokeColor: "#000000",
        backgroundColor: "#bfdbfe", // blue-200
        strokeWidth: 2,
        roughness: 2,
        opacity: 100,
        seed: 2,
    },
    {
        id: nanoid(),
        type: "text",
        x: 140,
        y: 240,
        width: 100,
        height: 30,
        strokeColor: "#1e3a8a",
        backgroundColor: "transparent",
        strokeWidth: 1,
        roughness: 1,
        opacity: 100,
        text: "Projects",
        link: "https://github.com", // Example link
        seed: 3,
    },
    {
        id: nanoid(),
        type: "arrow",
        x: 320,
        y: 250,
        width: 100,
        height: 0,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        strokeWidth: 2,
        roughness: 1,
        opacity: 100,
        points: [{ x: 320, y: 250 }, { x: 420, y: 250 }],
        seed: 4,
    },
    {
        id: nanoid(),
        type: "rectangle",
        x: 440,
        y: 200,
        width: 200,
        height: 100,
        strokeColor: "#000000",
        backgroundColor: "#bbf7d0", // green-200
        strokeWidth: 2,
        roughness: 2,
        opacity: 100,
        seed: 5,
    },
    {
        id: nanoid(),
        type: "text",
        x: 490,
        y: 240,
        width: 100,
        height: 30,
        strokeColor: "#14532d",
        backgroundColor: "transparent",
        strokeWidth: 1,
        roughness: 1,
        opacity: 100,
        text: "About Me",
        seed: 6,
    },
];
